main/urls.py
from django.urls import path
from . import views
from django.views.decorators.cache import cache_page

app_name = 'main'

urlpatterns = [
    path('', views.index, name="home"),
    path('subscribe/', views.add_email, name="add-email"),
    path('validate/', views.email_validation, name="validate_email"),
]

src/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
]

main/models.py
from django.conf import settings
from django.core.mail import send_mail
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver



class Card(models.Model):
    index_no = models.CharField(max_length=10)
    content = models.TextField()
    said_by = models.CharField(max_length=50)
    insta_link = models.CharField(max_length=100, default="")
    likes = models.IntegerField(default=0, blank=True, null=True)
    date_created = models.DateField(auto_now_add=True)

    def __str__(self):
        '''
        string repr of card instances
        '''
        return self.content


class EmailStore(models.Model):
    email = models.CharField(max_length=255)

    def __str__(self):
        return self.email

# @receiver(post_save, sender=Card)
# # sender to ensure receiver is only invoked when signal is sent by Card Model save
# def post_card_save_email_send(sender, created, instance, **kwargs):
#     if created:
#         all_mailing_list = EmailStore.objects.all()
#         subject = 'New post'
#         quote = Card.objects.order_by('-id')[0]

#         message = quote.content + ' by ' + quote.said_by 

#         send_mail(subject=subject, message=message, from_email='hello@xyz.com', recipient_list=all_mailing_list, fail_silently=False)

main/views.py
from django.contrib import messages
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from django.http import JsonResponse
#from django.views.decorators.cache import cache_page

from .models import Card, EmailStore

def index(request):
    """Displays all cards with pagination"""
    quotes = Card.objects.all()
    paginator = Paginator(quotes, 6)
    
    # getting the requested page number
    page_number = request.GET.get('page', 1)
    page_obj = paginator.get_page(page_number)

    context = {'page_obj': page_obj}
    return render(request, 'motivation.html', context)


def email_service_provider_valid(email):
    """Checking the email-service provider"""

    email_domains = ['@gmail.com', '@hotmail.com', '@yahoo.com']
    for d in email_domains:
        if str(email).endswith(d):
            return True

    return False

def add_email(request):
    """ajax post handling, data coming from frontend checked at backend
       & sent back as a JSON response 
    """
    email_value = request.POST.get('email_val', None)
    data = {}
    if not EmailStore.objects.filter(email=email_value).exists() and str(email_value).split('@')[0].islower():
        if email_service_provider_valid(email_value):
            email_store = EmailStore.objects.create(email=email_value)
            email_store.save()
            data['status'] = True
        
        else:
            data['status'] = False
    else:
        data['status'] = False

    return JsonResponse(data)


def email_validation(request):
    """checking email already taken or not"""
    email_val = request.GET.get('entered_email', None)
    data = {}
    if EmailStore.objects.filter(email=email_val).exists():
        data['is_taken'] = True

    return JsonResponse(data)

templates/motivation.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>Welcome | inspire.me</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1">
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Quicksand&display=swap" rel="stylesheet"> 
    <link href="https://fonts.googleapis.com/css2?family=Inconsolata:wght@200&display=swap" rel="stylesheet"> 
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'default.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>

<body>
    <section class="s1">
        <div class="main-container">
            <div class="navigation-bar">
                <a class="brand" href="{% url 'main:home'%}"> inspire<span><b>.me</b></span></a>
                <a class="about" href="#about-sec">about</a>
            </div>
        </div>
    </section>

    <section class="s5">
        <div class="greeting-section">
            <div class="greeting-body">
                <h4>Scroll through. Get inspired !</h4>
                <h6>For coders. By coders.</h6>

            </div>
        </div>
    </section>

    <section class="s2">
        <div class="card-container">
            <div class="card-wrapper">
                <!--1st card-->
                {% for quote in page_obj %}
                    <div class="motivation-item">
                        <div class="quote-no">
                            <h4>#{{quote.index_no}}</h4>
                        </div>

                        <div class="motivation-item-wrap">
                            <h4 class="quote">{{quote.content}}</h4>
                        </div>

                        <div class="other-info">
                            <div class="author">
                                <span>{{quote.said_by}}</span>
                                <a target="_blank" id="insta" class="fa fa-instagram" href={{quote.insta_link}}></a>
                            </div>
                            <span class="resource-date">{{quote.date_created}}</span>

                        </div>
                    </div>
                {% endfor %}    
            </div>
        </div>

    </section>

    <!-- pagination-->
    <section class="s6">
        <div class="main-container">
            <div class="pagination-block">
                <ul id="number">
                    {% if page_obj.has_previous %}
                        <li><a href="?page={{ page_obj.previous_page_number }}">&lt;</a></li>
                    {% endif %}

                    <span class="current">
                        {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                    </span>
                    
                    {% if page_obj.has_next %}
                        <li><a href="?page={{page_obj.next_page_number}}">&gt;</a> </li>
                    {% endif %}
                </ul>
            </div>

        </div>
    </section>

    <section class="s3">
        <div class="main-container">
            <div class="about-section">
                <h4 class="header" id="about-sec">about</h4>
                <h4 class="faq-question">What is inspire.me ?</h4>
                <p class="faq-answer">There's always a need for motivation. I personally needed it while learning coding, many seek for it. Hence this page was created which comprises of short motivational lines said by other coders out there. </p>
                
                <h4 class="faq-question">Are these some famous motivational quotes ? </h4>
                <p class="faq-answer">One can say that, but no these quotes are purely said by different coders out there, who were once or are a learner, speaking out the bitter truth & motivation related to it in this field </p>
                
                <h4 class="faq-question">How does this newsletter works ? </h4>
                <p class="faq-answer">Everytime a new quote or saying is uploaded, all subscribed users will receive an update of that quote via mail provided. </p>
            </div>

        </div>
    </section>

    <section class="s7"> 
        <div class="mail-wrapper">
        
            <form action="{% url 'main:add-email' %}" method="POST" class="sub-form" id="email-form">
                {% csrf_token %}
                
                <div class="subscribe-wrapper">    
                    <h4>Subscribe to my newsletter</h4>
                    <input type="email" id="email-field" name="email" class="subscribe-input" placeholder="Your email" required >
                    <div class="submit-btn">
                        <input type="submit" value="SUBMIT" class="submit-click"> 
                    </div>
                    {% if messages %}
                    {% for message in messages %}
                    <div class="alert">
                        <p style="font-family: 'Quicksand', sans-serif;">{{message}}</p>
                    </div>
                    {% endfor %}
                    {% endif %}
                </div>    
            </form> 
        </div>
    </section>

    <section class="s4">
        <div class="footer">
            <p class="footer-content">Made with ❤️ by <a target="_blank" href="https://www.instagram.com/brocode.py/">@brocode.py</a></p>
        </div> 
    </section>

    <script>
        $("#email-field").change(function(){var a=$(this).val();$.ajax({type:"GET",url:"{% url 'main:validate_email' %}",data:{entered_email:a},dataType:"json",success:function(a){a.is_taken&&($("#email-field").val("Already exists"),$("#email-field").css("background-color","#FF0000"))}})});
    </script>
        
    <script type="text/javascript">
        $("#email-form").submit(function(a){a.preventDefault();var t=$(this).attr("action"),e=$(".subscribe-input").val();$.ajax({type:"POST",url:t,data:{email_val:e,csrfmiddlewaretoken:"{{ csrf_token }}"},success:function(a){a.status?(alert("Thanks for joining"),$("#email-field").val("")):alert("Invalid")}})});
    </script>
</body>